sonar.projectKey=lissetsofia_Software-con-IA-Language-Tool-para-Generar-Cuadernillos-Mediante-Banco-de-Preguntas-de-Ex-menes-
sonar.organization=lissetsofia

sonar.sources=backend
sonar.tests=backend/test

sonar.test.inclusions=backend/test/test_*.py

sonar.coverage.exclusions=backend/test/**

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/uploads/**,**/descargas/**,**/data/**,**/html_cache/**,**/jre/**,**/libs/**

sonar.test.inclusions=**/test_*.py,**/*_test.py

sonar.python.coverage.reportPaths=coverage.xml