name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Analisis SonarCloud con cobertura Python
    runs-on: windows-latest
  
    env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Habilitar rutas largas en Git
        run: git config --global core.longpaths true

      - name: Descargar codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install flask flask-cors werkzeug requests python-docx pypdf mammoth reportlab docx2pdf pywin32

      - name: Ejecutar pruebas Python y generar cobertura
        run: |
          python -m pytest backend/test --cov=backend --cov-report=xml:coverage.xml

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias frontend
        run: npm install

      - name: Ejecutar tests frontend
        run: npm run test:frontend

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=lissetsofia_Software-con-IA-Language-Tool-para-Generar-Cuadernillos-Mediante-Banco-de-Preguntas-de-Ex-menes-
            -Dsonar.organization=lissetsofia
            -Dsonar.sources=backend,frontend
            -Dsonar.tests=backend/test,frontend/__tests__
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/__tests__/**,frontend/libs/**